package com.crackit.afyadaktari.utils;

public class Constants {
    public static final String KEY_USERNAME = "username";
    public static final String KEY_MOBILE = "mobile";
    public static final String KEY_CONFIRM_MOBILE = "confirm_mobile";
    public static final String KEY_PASSWORD = "password";
    public static final String KEY_NEW_PASSWORD = "new_password";
    public static final String KEY_CURRENT_PASSWORD = "current_password";
    public static final String KEY_USER_ID = "user_id";
    public static final String KEY_CONFIRM_PASSWORD = "confirm_password";
    public static final String KEY_TOKEN = "token";
    public static final String KEY_DATA_PAYLOAD = "DataPayload";
    public static final String KEY_TOAST_PAYLOAD = "ToastPayload";
    public static final String KEY_DATA = "data";
    public static final String KEY_TOAST = "toast";
    public static final String KEY_MESSAGE = "message";
    public static final String KEY_OTP_VALIDITY = "otp_validity";
    public static final String KEY_ERROR_PAYLOAD = "ErrorPayload";
    public static final String KEY_ERRORS = "errors";
    public static final String KEY_OTP = "otp";
    public static final String KEY_PROFILE_UPDATED = "profile_updated";
    public static final String KEY_MOBILE_VERIFIED = "mobile_verified";
    public static final String KEY_USERNAME_OR_MOBILE = "username_or_mobile";
    public static Long REGISTER_PHONE_VERIFICATION_TIMEOUT = 120L * 1000L;
    public static Long FORGOT_PASS_PHONE_VERIFICATION_TIMEOUT = 120L * 1000L;
    public static final long TOKEN_VALIDITY = 10 * 60 * 60;
    public static final String JWT_SECRET = "asfSFS34wfsdfsdfSDSD32asfSFS34wfsdfsasdfSFS34wfsdfsdfSDSD32dfsDDerSNACK34SOWED5354fdgdf4dfSDSD32dfsddDDerQSNCK34SOWED5354fdgdf4dfsddDDerQSNCK34SOWED5354fdgdf4";
    public static final String REGISTER_SUCCESS_MESSAGE = "Registration successful. An OTP has been sent to verify your phone number.";
    public static final String FORGOT_PASSWORD_REQ_SUCCESS = "A one time pin has successfully been sent to your mobile for verification.";
    public static final String RESET_PASSWORD_SUCCESS = "Your password reset was a success.";
    public static final String CHANGE_PASSWORD_SUCCESS = "Your password has been changed successfully.";
    public static final String LOGIN_SUCCESS_MESSAGE = "You have logged in successfully.";
    public static final String INVALID_TOKEN_MESSAGE = "Your request was made with invalid credentials";
    public static final String EMPTY_TOKEN_MESSAGE = "Hey you! Make sure you have a token before requesting for anything.";
    public static final String EXPIRED_TOKEN_MESSAGE = "Your session has already expired";
    public static final String OTP_VERIFICATION_SUCCESS_MESSAGE = "OTP verified successfully";
    public static final String OTP_RESEND_SUCCESS_MESSAGE = "OTP was re sent to your mobile successfully";
    public static final String BAD_CREDENTIALS_MESSAGE = "Bad credentials";
}
